import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";
import { logger } from "../../logger";

// ── Categories ──────────────────────────────────────────────────────────────

const CATEGORIES = [
  "Herbs & Spices",
  "Vegetables",
  "Fruits",
  "Meats & Seafood",
  "Dairy & Eggs",
  "Grains & Pasta",
  "Oils & Condiments",
  "Baking",
  "Canned & Jarred",
  "Nuts & Seeds",
  "Beverages",
  "Other",
] as const;

type Category = (typeof CATEGORIES)[number];

// ── Local keyword map ───────────────────────────────────────────────────────
// Longer / more-specific keys are checked first so "olive oil" matches
// Oils & Condiments rather than Vegetables ("olive").

const KEYWORD_MAP: [string, Category][] = [
  // ── Oils & Condiments (multi-word first) ─────────────────────────────────
  ["olive oil", "Oils & Condiments"],
  ["vegetable oil", "Oils & Condiments"],
  ["canola oil", "Oils & Condiments"],
  ["sesame oil", "Oils & Condiments"],
  ["coconut oil", "Oils & Condiments"],
  ["avocado oil", "Oils & Condiments"],
  ["peanut oil", "Oils & Condiments"],
  ["sunflower oil", "Oils & Condiments"],
  ["soy sauce", "Oils & Condiments"],
  ["fish sauce", "Oils & Condiments"],
  ["hot sauce", "Oils & Condiments"],
  ["oyster sauce", "Oils & Condiments"],
  ["hoisin sauce", "Oils & Condiments"],
  ["teriyaki sauce", "Oils & Condiments"],
  ["barbecue sauce", "Oils & Condiments"],
  ["bbq sauce", "Oils & Condiments"],
  ["worcestershire", "Oils & Condiments"],
  ["maple syrup", "Oils & Condiments"],
  ["vinegar", "Oils & Condiments"],
  ["ketchup", "Oils & Condiments"],
  ["mustard", "Oils & Condiments"],
  ["mayonnaise", "Oils & Condiments"],
  ["mayo", "Oils & Condiments"],
  ["honey", "Oils & Condiments"],
  ["sriracha", "Oils & Condiments"],
  ["tabasco", "Oils & Condiments"],
  ["salsa", "Oils & Condiments"],
  ["relish", "Oils & Condiments"],
  ["chutney", "Oils & Condiments"],
  ["miso", "Oils & Condiments"],
  ["tahini", "Oils & Condiments"],

  // ── Herbs & Spices ───────────────────────────────────────────────────────
  ["garlic powder", "Herbs & Spices"],
  ["onion powder", "Herbs & Spices"],
  ["chili powder", "Herbs & Spices"],
  ["chilli powder", "Herbs & Spices"],
  ["curry powder", "Herbs & Spices"],
  ["five spice", "Herbs & Spices"],
  ["bay leaf", "Herbs & Spices"],
  ["bay leaves", "Herbs & Spices"],
  ["lemon grass", "Herbs & Spices"],
  ["lemongrass", "Herbs & Spices"],
  ["star anise", "Herbs & Spices"],
  ["black pepper", "Herbs & Spices"],
  ["white pepper", "Herbs & Spices"],
  ["red pepper flakes", "Herbs & Spices"],
  ["pepper flakes", "Herbs & Spices"],
  ["italian seasoning", "Herbs & Spices"],
  ["everything bagel", "Herbs & Spices"],
  ["salt", "Herbs & Spices"],
  ["pepper", "Herbs & Spices"],
  ["cumin", "Herbs & Spices"],
  ["paprika", "Herbs & Spices"],
  ["oregano", "Herbs & Spices"],
  ["thyme", "Herbs & Spices"],
  ["basil", "Herbs & Spices"],
  ["cinnamon", "Herbs & Spices"],
  ["turmeric", "Herbs & Spices"],
  ["cayenne", "Herbs & Spices"],
  ["rosemary", "Herbs & Spices"],
  ["nutmeg", "Herbs & Spices"],
  ["clove", "Herbs & Spices"],
  ["ginger", "Herbs & Spices"],
  ["dill", "Herbs & Spices"],
  ["parsley", "Herbs & Spices"],
  ["cilantro", "Herbs & Spices"],
  ["coriander", "Herbs & Spices"],
  ["sage", "Herbs & Spices"],
  ["tarragon", "Herbs & Spices"],
  ["chive", "Herbs & Spices"],
  ["mint", "Herbs & Spices"],
  ["fennel seed", "Herbs & Spices"],
  ["cardamom", "Herbs & Spices"],
  ["allspice", "Herbs & Spices"],
  ["saffron", "Herbs & Spices"],
  ["sumac", "Herbs & Spices"],
  ["za'atar", "Herbs & Spices"],
  ["zaatar", "Herbs & Spices"],
  ["marjoram", "Herbs & Spices"],
  ["anise", "Herbs & Spices"],
  ["fenugreek", "Herbs & Spices"],
  ["smoked paprika", "Herbs & Spices"],
  ["seasoning", "Herbs & Spices"],

  // ── Vegetables ───────────────────────────────────────────────────────────
  ["bell pepper", "Vegetables"],
  ["green bean", "Vegetables"],
  ["green beans", "Vegetables"],
  ["green onion", "Vegetables"],
  ["spring onion", "Vegetables"],
  ["sweet potato", "Vegetables"],
  ["sweet potatoes", "Vegetables"],
  ["bok choy", "Vegetables"],
  ["brussels sprout", "Vegetables"],
  ["snow pea", "Vegetables"],
  ["sugar snap", "Vegetables"],
  ["water chestnut", "Vegetables"],
  ["bean sprout", "Vegetables"],
  ["artichoke", "Vegetables"],
  ["onion", "Vegetables"],
  ["garlic", "Vegetables"],
  ["carrot", "Vegetables"],
  ["potato", "Vegetables"],
  ["tomato", "Vegetables"],
  ["broccoli", "Vegetables"],
  ["spinach", "Vegetables"],
  ["celery", "Vegetables"],
  ["zucchini", "Vegetables"],
  ["mushroom", "Vegetables"],
  ["corn", "Vegetables"],
  ["lettuce", "Vegetables"],
  ["cabbage", "Vegetables"],
  ["cucumber", "Vegetables"],
  ["eggplant", "Vegetables"],
  ["asparagus", "Vegetables"],
  ["kale", "Vegetables"],
  ["cauliflower", "Vegetables"],
  ["pea", "Vegetables"],
  ["radish", "Vegetables"],
  ["turnip", "Vegetables"],
  ["beet", "Vegetables"],
  ["squash", "Vegetables"],
  ["pumpkin", "Vegetables"],
  ["leek", "Vegetables"],
  ["scallion", "Vegetables"],
  ["shallot", "Vegetables"],
  ["fennel", "Vegetables"],
  ["arugula", "Vegetables"],
  ["watercress", "Vegetables"],
  ["endive", "Vegetables"],
  ["chard", "Vegetables"],
  ["collard", "Vegetables"],
  ["okra", "Vegetables"],
  ["jalapeño", "Vegetables"],
  ["jalapeno", "Vegetables"],
  ["habanero", "Vegetables"],
  ["serrano", "Vegetables"],
  ["poblano", "Vegetables"],
  ["parsnip", "Vegetables"],
  ["rutabaga", "Vegetables"],
  ["yam", "Vegetables"],
  ["taro", "Vegetables"],
  ["jicama", "Vegetables"],
  ["daikon", "Vegetables"],

  // ── Fruits ───────────────────────────────────────────────────────────────
  ["apple", "Fruits"],
  ["banana", "Fruits"],
  ["lemon", "Fruits"],
  ["lime", "Fruits"],
  ["orange", "Fruits"],
  ["strawberry", "Fruits"],
  ["blueberry", "Fruits"],
  ["raspberry", "Fruits"],
  ["blackberry", "Fruits"],
  ["avocado", "Fruits"],
  ["mango", "Fruits"],
  ["pineapple", "Fruits"],
  ["grape", "Fruits"],
  ["peach", "Fruits"],
  ["pear", "Fruits"],
  ["watermelon", "Fruits"],
  ["coconut", "Fruits"],
  ["cherry", "Fruits"],
  ["cranberry", "Fruits"],
  ["pomegranate", "Fruits"],
  ["kiwi", "Fruits"],
  ["papaya", "Fruits"],
  ["fig", "Fruits"],
  ["date", "Fruits"],
  ["plum", "Fruits"],
  ["apricot", "Fruits"],
  ["cantaloupe", "Fruits"],
  ["honeydew", "Fruits"],
  ["grapefruit", "Fruits"],
  ["tangerine", "Fruits"],
  ["clementine", "Fruits"],
  ["guava", "Fruits"],
  ["passion fruit", "Fruits"],
  ["lychee", "Fruits"],
  ["dragon fruit", "Fruits"],
  ["raisin", "Fruits"],

  // ── Meats & Seafood ──────────────────────────────────────────────────────
  ["ground beef", "Meats & Seafood"],
  ["ground turkey", "Meats & Seafood"],
  ["ground pork", "Meats & Seafood"],
  ["chicken breast", "Meats & Seafood"],
  ["chicken thigh", "Meats & Seafood"],
  ["chicken wing", "Meats & Seafood"],
  ["chicken drumstick", "Meats & Seafood"],
  ["pork chop", "Meats & Seafood"],
  ["pork belly", "Meats & Seafood"],
  ["pork loin", "Meats & Seafood"],
  ["beef stew", "Meats & Seafood"],
  ["short rib", "Meats & Seafood"],
  ["chicken", "Meats & Seafood"],
  ["beef", "Meats & Seafood"],
  ["pork", "Meats & Seafood"],
  ["salmon", "Meats & Seafood"],
  ["shrimp", "Meats & Seafood"],
  ["prawn", "Meats & Seafood"],
  ["turkey", "Meats & Seafood"],
  ["bacon", "Meats & Seafood"],
  ["sausage", "Meats & Seafood"],
  ["lamb", "Meats & Seafood"],
  ["tuna", "Meats & Seafood"],
  ["cod", "Meats & Seafood"],
  ["crab", "Meats & Seafood"],
  ["lobster", "Meats & Seafood"],
  ["steak", "Meats & Seafood"],
  ["ham", "Meats & Seafood"],
  ["duck", "Meats & Seafood"],
  ["tilapia", "Meats & Seafood"],
  ["veal", "Meats & Seafood"],
  ["venison", "Meats & Seafood"],
  ["bison", "Meats & Seafood"],
  ["anchovy", "Meats & Seafood"],
  ["anchovies", "Meats & Seafood"],
  ["sardine", "Meats & Seafood"],
  ["scallop", "Meats & Seafood"],
  ["mussel", "Meats & Seafood"],
  ["clam", "Meats & Seafood"],
  ["oyster", "Meats & Seafood"],
  ["squid", "Meats & Seafood"],
  ["calamari", "Meats & Seafood"],
  ["octopus", "Meats & Seafood"],
  ["pepperoni", "Meats & Seafood"],
  ["salami", "Meats & Seafood"],
  ["prosciutto", "Meats & Seafood"],
  ["pancetta", "Meats & Seafood"],
  ["chorizo", "Meats & Seafood"],
  ["brisket", "Meats & Seafood"],
  ["meatball", "Meats & Seafood"],

  // ── Dairy & Eggs ─────────────────────────────────────────────────────────
  ["cream cheese", "Dairy & Eggs"],
  ["sour cream", "Dairy & Eggs"],
  ["whipping cream", "Dairy & Eggs"],
  ["heavy cream", "Dairy & Eggs"],
  ["half and half", "Dairy & Eggs"],
  ["cottage cheese", "Dairy & Eggs"],
  ["goat cheese", "Dairy & Eggs"],
  ["feta cheese", "Dairy & Eggs"],
  ["blue cheese", "Dairy & Eggs"],
  ["swiss cheese", "Dairy & Eggs"],
  ["cheddar", "Dairy & Eggs"],
  ["mozzarella", "Dairy & Eggs"],
  ["parmesan", "Dairy & Eggs"],
  ["ricotta", "Dairy & Eggs"],
  ["provolone", "Dairy & Eggs"],
  ["gruyere", "Dairy & Eggs"],
  ["brie", "Dairy & Eggs"],
  ["milk", "Dairy & Eggs"],
  ["cheese", "Dairy & Eggs"],
  ["butter", "Dairy & Eggs"],
  ["egg", "Dairy & Eggs"],
  ["eggs", "Dairy & Eggs"],
  ["yogurt", "Dairy & Eggs"],
  ["cream", "Dairy & Eggs"],
  ["ghee", "Dairy & Eggs"],
  ["whey", "Dairy & Eggs"],
  ["buttermilk", "Dairy & Eggs"],

  // ── Grains & Pasta ───────────────────────────────────────────────────────
  ["rice", "Grains & Pasta"],
  ["pasta", "Grains & Pasta"],
  ["spaghetti", "Grains & Pasta"],
  ["penne", "Grains & Pasta"],
  ["macaroni", "Grains & Pasta"],
  ["linguine", "Grains & Pasta"],
  ["fettuccine", "Grains & Pasta"],
  ["rigatoni", "Grains & Pasta"],
  ["orzo", "Grains & Pasta"],
  ["lasagna", "Grains & Pasta"],
  ["noodle", "Grains & Pasta"],
  ["flour", "Grains & Pasta"],
  ["bread", "Grains & Pasta"],
  ["oat", "Grains & Pasta"],
  ["quinoa", "Grains & Pasta"],
  ["couscous", "Grains & Pasta"],
  ["tortilla", "Grains & Pasta"],
  ["cornmeal", "Grains & Pasta"],
  ["barley", "Grains & Pasta"],
  ["breadcrumb", "Grains & Pasta"],
  ["cereal", "Grains & Pasta"],
  ["cracker", "Grains & Pasta"],
  ["panko", "Grains & Pasta"],
  ["pita", "Grains & Pasta"],
  ["flatbread", "Grains & Pasta"],
  ["bagel", "Grains & Pasta"],
  ["croissant", "Grains & Pasta"],
  ["bun", "Grains & Pasta"],
  ["ramen", "Grains & Pasta"],
  ["udon", "Grains & Pasta"],
  ["soba", "Grains & Pasta"],
  ["bulgur", "Grains & Pasta"],
  ["polenta", "Grains & Pasta"],
  ["grits", "Grains & Pasta"],
  ["millet", "Grains & Pasta"],
  ["farro", "Grains & Pasta"],
  ["wheat", "Grains & Pasta"],

  // ── Baking ───────────────────────────────────────────────────────────────
  ["baking powder", "Baking"],
  ["baking soda", "Baking"],
  ["vanilla extract", "Baking"],
  ["almond extract", "Baking"],
  ["cocoa powder", "Baking"],
  ["chocolate chip", "Baking"],
  ["powdered sugar", "Baking"],
  ["confectioner", "Baking"],
  ["brown sugar", "Baking"],
  ["granulated sugar", "Baking"],
  ["sugar", "Baking"],
  ["yeast", "Baking"],
  ["cornstarch", "Baking"],
  ["molasses", "Baking"],
  ["gelatin", "Baking"],
  ["food coloring", "Baking"],
  ["sprinkles", "Baking"],
  ["frosting", "Baking"],
  ["icing", "Baking"],

  // ── Canned & Jarred ──────────────────────────────────────────────────────
  ["tomato paste", "Canned & Jarred"],
  ["tomato sauce", "Canned & Jarred"],
  ["canned tomato", "Canned & Jarred"],
  ["crushed tomato", "Canned & Jarred"],
  ["diced tomato", "Canned & Jarred"],
  ["coconut milk", "Canned & Jarred"],
  ["coconut cream", "Canned & Jarred"],
  ["peanut butter", "Canned & Jarred"],
  ["almond butter", "Canned & Jarred"],
  ["broth", "Canned & Jarred"],
  ["stock", "Canned & Jarred"],
  ["bouillon", "Canned & Jarred"],
  ["chickpea", "Canned & Jarred"],
  ["garbanzo", "Canned & Jarred"],
  ["lentil", "Canned & Jarred"],
  ["black bean", "Canned & Jarred"],
  ["kidney bean", "Canned & Jarred"],
  ["pinto bean", "Canned & Jarred"],
  ["navy bean", "Canned & Jarred"],
  ["cannellini", "Canned & Jarred"],
  ["bean", "Canned & Jarred"],
  ["jam", "Canned & Jarred"],
  ["jelly", "Canned & Jarred"],
  ["preserve", "Canned & Jarred"],
  ["pickle", "Canned & Jarred"],
  ["olive", "Canned & Jarred"],
  ["caper", "Canned & Jarred"],
  ["sun-dried tomato", "Canned & Jarred"],
  ["marinara", "Canned & Jarred"],
  ["pasta sauce", "Canned & Jarred"],
  ["enchilada sauce", "Canned & Jarred"],
  ["curry paste", "Canned & Jarred"],
  ["tofu", "Canned & Jarred"],
  ["tempeh", "Canned & Jarred"],

  // ── Nuts & Seeds ─────────────────────────────────────────────────────────
  ["sunflower seed", "Nuts & Seeds"],
  ["sesame seed", "Nuts & Seeds"],
  ["chia seed", "Nuts & Seeds"],
  ["flax seed", "Nuts & Seeds"],
  ["flaxseed", "Nuts & Seeds"],
  ["poppy seed", "Nuts & Seeds"],
  ["pumpkin seed", "Nuts & Seeds"],
  ["pine nut", "Nuts & Seeds"],
  ["almond", "Nuts & Seeds"],
  ["walnut", "Nuts & Seeds"],
  ["peanut", "Nuts & Seeds"],
  ["cashew", "Nuts & Seeds"],
  ["pecan", "Nuts & Seeds"],
  ["pistachio", "Nuts & Seeds"],
  ["hazelnut", "Nuts & Seeds"],
  ["macadamia", "Nuts & Seeds"],
  ["brazil nut", "Nuts & Seeds"],
  ["chestnut", "Nuts & Seeds"],

  // ── Beverages ────────────────────────────────────────────────────────────
  ["coffee", "Beverages"],
  ["espresso", "Beverages"],
  ["tea", "Beverages"],
  ["juice", "Beverages"],
  ["wine", "Beverages"],
  ["beer", "Beverages"],
  ["vodka", "Beverages"],
  ["rum", "Beverages"],
  ["whiskey", "Beverages"],
  ["bourbon", "Beverages"],
  ["tequila", "Beverages"],
  ["gin", "Beverages"],
  ["brandy", "Beverages"],
  ["sake", "Beverages"],
  ["mirin", "Beverages"],
  ["sherry", "Beverages"],
  ["marsala", "Beverages"],
  ["soda", "Beverages"],
  ["sparkling water", "Beverages"],
  ["lemonade", "Beverages"],
];

// Sort by key length descending so longer (more specific) matches win.
KEYWORD_MAP.sort((a, b) => b[0].length - a[0].length);

// ── Phase 1: Instant local categorization ───────────────────────────────────

/**
 * Synchronously categorizes a single ingredient name using the local
 * keyword map. Returns "Other" for unrecognized ingredients.
 */
function categorize(name: string): Category {
  const lower = name.toLowerCase().trim();
  for (const [keyword, category] of KEYWORD_MAP) {
    if (lower.includes(keyword)) {
      return category;
    }
  }
  return "Other";
}

// ── Phase 2: Background AI refinement ───────────────────────────────────────

const categoryEnum = z.enum(
  CATEGORIES as unknown as [string, ...string[]],
);

const aiCategorizationSchema = z.object({
  items: z.array(
    z.object({
      name: z.string(),
      category: categoryEnum,
    }),
  ),
});

/**
 * Uses AI to classify ingredient names that the local map could not handle.
 * Returns a map of ingredient name → category.
 */
async function classifyWithAI(
  names: string[],
): Promise<Map<string, string>> {
  const result = new Map<string, string>();
  if (names.length === 0) return result;

  try {
    const { object } = await generateObject({
      model: openai("gpt-4o-mini"),
      schema: aiCategorizationSchema,
      messages: [
        {
          role: "system",
          content: `You are a food categorization assistant. Classify each ingredient into exactly one of these categories: ${CATEGORIES.join(", ")}. If unsure, use "Other".`,
        },
        {
          role: "user",
          content: `Classify these ingredients:\n${names.join("\n")}`,
        },
      ],
    });

    for (const item of object.items) {
      result.set(item.name.toLowerCase().trim(), item.category);
    }
  } catch (error) {
    logger.error("AI ingredient categorization failed:", error);
    // Silently fall back — items stay as "Other"
  }

  return result;
}

export { categorize, classifyWithAI, CATEGORIES, type Category };
